name: Build Installers

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            task: jpackageMac
          - os: windows-latest
            task: jpackageWin
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install WiX Toolset
        if: runner.os == 'Windows'
        run: |
          curl -OL https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          Expand-Archive wix311-binaries.zip -DestinationPath C:\wix311
          echo "C:\wix311" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Make Gradle wrapper executable
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          java -version
          ./gradlew ${{ matrix.task }} --info --stacktrace

      - name: Upload installer
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: installer-${{ matrix.os }}
          path: |
            build/jpackage/*.exe
            build/jpackage/*.pkg
            build/jpackage/*.dmg
          if-no-files-found: warn

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download all installers
        uses: actions/download-artifact@v3

      - name: List downloaded files
        run: ls -R

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            installer-windows-latest/*.exe
            installer-macos-latest/*.pkg
            installer-macos-latest/*.dmg
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}